"""Shared translation core used by direct and lazy translation pathways."""

from __future__ import annotations

from .models import FactBundle, SnakeConfig, ToolExpansionStat, ToolMode
from .ontology import Ontology
from .translator import (
    _FactWriter,
    _ExpansionResolver,
    _assign_lazy_signature_profiles,
    _build_common_facts,
    _build_roots,
    _collect_compressed_lazy_bindability_surface,
    _collect_lazy_backward_relevant_candidates,
    _collect_lazy_exact_prefix_lower_bound,
    _collect_lazy_forbidden_tool_ids,
    _collect_lazy_selector_lower_bounds,
    _compress_duplicate_output_ports,
    _compress_lazy_output_choice_values,
    _dedupe_stable,
    _finalize_fact_bundle,
    _group_port_values_by_dimension,
    _lazy_dim_values_cache_key,
    _lazy_output_matches_lazy_input_fset,
    _lazy_port_expansion,
    _normalize_dim_map,
    _product,
    _quote,
    _workflow_input_matches_lazy_port,
    _compute_lazy_candidate_min_steps,
    build_fact_bundle,
    build_fact_bundle_ape_multi_shot,
    _emit_lazy_constraints,
)

__all__ = (
    "FactBundle",
    "SnakeConfig",
    "ToolExpansionStat",
    "ToolMode",
    "Ontology",
    "_FactWriter",
    "_ExpansionResolver",
    "_assign_lazy_signature_profiles",
    "_build_common_facts",
    "_build_roots",
    "_collect_compressed_lazy_bindability_surface",
    "_collect_lazy_backward_relevant_candidates",
    "_collect_lazy_exact_prefix_lower_bound",
    "_collect_lazy_forbidden_tool_ids",
    "_collect_lazy_selector_lower_bounds",
    "_compress_duplicate_output_ports",
    "_compress_lazy_output_choice_values",
    "_dedupe_stable",
    "_emit_lazy_constraints",
    "_finalize_fact_bundle",
    "_group_port_values_by_dimension",
    "_lazy_dim_values_cache_key",
    "_lazy_output_matches_lazy_input_fset",
    "_lazy_port_expansion",
    "_normalize_dim_map",
    "_product",
    "_quote",
    "_workflow_input_matches_lazy_port",
    "_compute_lazy_candidate_min_steps",
    "build_fact_bundle",
    "build_fact_bundle_ape_multi_shot",
)
